<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aptechka.Application\Aptechka.Application.csproj" />
    <ProjectReference Include="..\Aptechka.Domain\Aptechka.Domain.csproj" />
  </ItemGroup>

</Project>
